---
- name: Generating Terraform AWS Cloudfront
  template:
    src: templates/aws/terraform_aws_cloudfront.tf.j2
    dest: "{{ terraform_project_path }}/aws_cloudfront.tf"

- name: Generating Terraform AWS Cloudfront function
  template:
    src: templates/aws/terraform_aws_cloudfront_auth_function.js.j2
    dest: "{{ terraform_project_path }}/aws_cloudfront_auth_function.js"