---
- name: Generating Terraform Azure CDN
  template:
    src: templates/terraform_azure_cdn.tf.j2
    dest: "{{ terraform_project_path }}/azure_cdn.tf"

- name: Generating Terraform Azure Resource
  template:
    src: templates/terraform_azure_resource.tf.j2
    dest: "{{ terraform_project_path }}/azure_resource.tf"

- include: azure_appservice.yml