- name: Destroy Terraform Remote State
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    backend_config:
      region: "{{ warhorse.terraform.state_bucket_region }}"
      bucket: "{{ warhorse.terraform.state_bucket_name }}"
      key: "{{ warhorse.terraform.state_bucket_key }}"
      access_key: "{{ bucket_access_key }}"
      secret_key: "{{ bucket_secret_key }}"
      endpoint: "{{ warhorse.terraform.state_bucket_endpoint }}"
    force_init: true
    variables:
      "{{ token }}": "{{ token_value }}"
  when: warhorse.terraform.state_bucket_enabled is defined and true

- name: Destroy Terraform Cloud
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    workspace: "{{ warhorse.terraform.cloud_workspace }}"
    force_init: true
    variables:
      "{{ token }}": "{{ token_value }}"
  when: warhorse.terraform.cloud_enabled is defined and true

- name: Destroy Terraform Local State
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    force_init: true
    variables:
      "{{ token }}": "{{ token_value }}"
  when: warhorse.terraform.state_bucket_enabled is not defined and warhorse.terraform.cloud_enabled is not defined
