---
- name: Generating Terraform Digital Ocean Droplet
  template:
    src: templates/digitalocean/terraform_digitalocean_do.tf.j2
    dest: "{{ terraform_project_path }}/digitalocean_do.tf"
  with_items: "{{ warhorse.vm }}"
  when: item.provider == 'digitalocean'

- name: Generating Terraform Digital Ocean DNS
  template:
    src: templates/digitalocean/terraform_digitalocean_dns.tf.j2
    dest: "{{ terraform_project_path }}/digitalocean_dns.tf"
  when: warhorse.dns.provider == 'digitalocean'

- name: Generating Terraform CloudInit
  template:
    src: templates/digitalocean/cloud-init-do.yaml.j2
    dest: "{{ terraform_project_path }}/cloud-init-do.yaml"
  with_items: "{{ warhorse.vm }}"
  when: item.provider == 'digitalocean'