---
- name: Create a terraform directorys 
  ansible.builtin.file:
    path: '{{ item.folder }}'
    state: directory
    mode: '0755'
  with_items:
  - folder: "{{ terraform_project_path }}/linode"

- name: Generating Terraform Linode Instance
  template:
    src: templates/linode/terraform_linode_li.tf.j2
    dest: "{{ terraform_project_path }}/linode_li.tf"
  with_items: "{{ warhorse.vm }}"
  when: item.provider == 'linode'

- name: Generating Terraform Linode DNS
  template:
    src: templates/linode/terraform_linode_dns.tf.j2
    dest: "{{ terraform_project_path }}/linode_dns.tf"
  when: warhorse.dns == 'linode'

# - name: Generating Terraform CloudInit
#   template:
#     src: templates/linode/cloud-init-do.yaml.j2
#     dest: "{{ terraform_project_path }}/cloud-init-do.yaml"
#   with_items: "{{ warhorse.vm }}"
#   when: item.provider == 'linode'