---
- include: generate.yml

- include: remote.yml
  vars:
    state: "present"
    name: "Deploy"
  when: deploy and warhorse.terraform.state_bucket_enabled is defined and true

- include: cloud.yml
  vars:
    state: "present"
    name: "Deploy"
  when: deploy and warhorse.terraform.cloud_enabled is defined and true

- include: local.yml
  vars:
    state: "present"
    name: "Deploy"
  when: deploy and warhorse.terraform.state_bucket_enabled is not defined and warhorse.terraform.cloud_enabled is not defined

- include: remote.yml
  vars:
    state: "absent"
    name: "Destroy"
  when: not deploy and warhorse.terraform.state_bucket_enabled is defined and true

- include: cloud.yml
  vars:
    state: "absent"
    name: "Destroy"
  when: not deploy and warhorse.terraform.cloud_enabled is defined and true

- include: local.yml
  vars:
    state: "absent"
    name: "Destroy"
  when: not deploy and warhorse.terraform.state_bucket_enabled is not defined and warhorse.terraform.cloud_enabled is not defined
