---
- name: Create Folders
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - './OP'
  - './OP/{{ warhorse.general.op_number }}'
  - './OP/{{ warhorse.general.op_number }}/inventory'
  - './OP/{{ warhorse.general.op_number }}/files'
  - './OP/{{ warhorse.general.op_number }}/keys'