---
- name: Generating deploy.yml
  template:
    mode: '0755'
    src: templates/deploy.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/deploy.yml"

- name: Generating destroy.yml
  template:
    mode: '0755'
    src: templates/destroy.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/destroy.yml"