---
- name: Generating os inventory
  template:
    mode: '0755'
    src: templates/os.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/os.yml"

- name: Generating vault
  template:
    mode: '0755'
    src: templates/vault.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/vault.yml"

- name: Encrypt vault
  ansible.builtin.shell: ansible-vault encrypt "{{ lookup('env', 'PWD') }}"/OP/{{ warhorse.general.op_number }}/inventory/vault.yml
  environment: 
    ANSIBLE_VAULT_PASSWORD: "{{ warhorse.general.vault_key }}"
    ANSIBLE_VAULT_PASSWORD_FILE: "./vault-env"

- name: Generating dns inventory
  template:
    mode: '0755'
    src: templates/dns.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/dns.yml"

- name: Generating syncthing inventory
  template:
    mode: '0755'
    src: templates/syncthing.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/syncthing.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.syncthing is defined and item.syncthing.enabled

- name: Generating firewall inventory
  template:
    mode: '0755'
    src: templates/firewall.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/firewall.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.firewall is defined and item.firewall.enabled

- name: Generating cobaltstrike inventory
  template:
    mode: '0755'
    src: templates/cobaltstrike.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/cobaltstrike.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.cobaltstrike is defined and item.cobaltstrike.enabled

- name: Generating nighthawk inventory
  template:
    mode: '0755'
    src: templates/nighthawk.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/nighthawk.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.nighthawk is defined and item.nighthawk.enabled

- name: Generating gophish inventory
  template:
    mode: '0755'
    src: templates/gophish.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/gophish.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.gophish is defined and item.gophish.enabled

- name: Generating mythic inventory
  template:
    mode: '0755'
    src: templates/mythic.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/mythic.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.mythic is defined and item.mythic.enabled


- name: Generating traefik inventory
  template:
    mode: '0755'
    src: templates/traefik.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/traefik.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.http_proxy == "traefik"

- name: Generating neo4j inventory
  template:
    mode: '0755'
    src: templates/neo4j.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/neo4j.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.neo4j is defined and item.neo4j.enabled

- name: Generating evilginx2 inventory
  template:
    mode: '0755'
    src: templates/evilginx2.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/evilginx2.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.evilginx2 is defined and item.evilginx2.enabled

- name: Generating tailscale inventory
  template:
    mode: '0755'
    src: templates/tailscale.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/tailscale.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.tailscale is defined and item.tailscale.enabled

- name: Generating nginx inventory
  template:
    mode: '0755'
    src: templates/nginx.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/nginx.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.http_proxy == "nginx"

- name: Generating backup inventory
  template:
    mode: '0755'
    src: templates/backup.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/inventory/backup.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.backup is defined and item.backup.enabled