---
- name: Generating os inventory
  template:
    mode: '0755'
    src: templates/os.yml.j2
    dest: "./inventory/os.yml"

- name: Generating vault
  template:
    mode: '0755'
    src: templates/vault.yml.j2
    dest: "./inventory/vault.yml"

- name: Encrypt vault
  ansible.builtin.shell: ansible-vault encrypt "{{ lookup('env', 'PWD') }}"/inventory/vault.yml
  environment: 
    ANSIBLE_VAULT_PASSWORD: "{{ warhorse.general.vault_key }}"
    ANSIBLE_VAULT_PASSWORD_FILE: "./vault-env"

- name: Generating dns inventory
  template:
    mode: '0755'
    src: templates/dns.yml.j2
    dest: "./inventory/dns.yml"

- name: Generating firewall inventory
  template:
    mode: '0755'
    src: templates/firewall.yml.j2
    dest: "./inventory/firewall.yml"
  with_items: "{{ warhorse.vm }}"
  when: item.firewall.enabled

- name: Generating cobaltstrike inventory
  template:
    mode: '0755'
    src: templates/cobaltstrike.yml.j2
    dest: "./inventory/cobaltstrike.yml"

- name: Generating traefik inventory
  template:
    mode: '0755'
    src: templates/traefik.yml.j2
    dest: "./inventory/traefik.yml"

- name: Generating neo4j inventory
  template:
    mode: '0755'
    src: templates/neo4j.yml.j2
    dest: "./inventory/neo4j.yml"

- name: Generating evilginx2 inventory
  template:
    mode: '0755'
    src: templates/evilginx2.yml.j2
    dest: "./inventory/evilginx2.yml"

- name: Generating tailscale inventory
  template:
    mode: '0755'
    src: templates/tailscale.yml.j2
    dest: "./inventory/tailscale.yml"