---
- name: Generating nginx Configuration
  template:
    mode: '0755'
    src: templates/nginx_config.yml.j2
    dest: "./OP/{{ warhorse.general.op_number }}/files/{{ item.name }}/nginx_config.yml.j2"
  with_items:
  - '{{ warhorse.vm }}'